//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSIT126_Project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbMSIT126Team02Entities1 : DbContext
    {
        public dbMSIT126Team02Entities1()
            : base("name=dbMSIT126Team02Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tAluminumMaterialList> tAluminumMaterialList { get; set; }
        public virtual DbSet<tCheck> tCheck { get; set; }
        public virtual DbSet<tCustomers> tCustomers { get; set; }
        public virtual DbSet<tDepartment> tDepartment { get; set; }
        public virtual DbSet<tEmployee> tEmployee { get; set; }
        public virtual DbSet<tGlass> tGlass { get; set; }
        public virtual DbSet<tJobTitle> tJobTitle { get; set; }
        public virtual DbSet<tOrderComment> tOrderComment { get; set; }
        public virtual DbSet<tOrderDetail> tOrderDetail { get; set; }
        public virtual DbSet<tOrders> tOrders { get; set; }
        public virtual DbSet<tProduct> tProduct { get; set; }
        public virtual DbSet<tProductList> tProductList { get; set; }
    }
}
