//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCase
    {
        public int fCaseID { get; set; }
        public string fheading { get; set; }
        public string fcontent { get; set; }
        public Nullable<int> fCustomerID { get; set; }
    
        public virtual tCustomer tCustomer { get; set; }
    }
}
