//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCustomer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tCustomer()
        {
            this.tCases = new HashSet<tCase>();
            this.tChecks = new HashSet<tCheck>();
            this.tNews = new HashSet<tNew>();
            this.tOrders = new HashSet<tOrder>();
        }
    
        public int fCustomerID { get; set; }
        public Nullable<int> fEmployeeID { get; set; }
        public string fUserName { get; set; }
        public string fCompanyName { get; set; }
        public string fTaxID { get; set; }
        public string fContactName { get; set; }
        public string fTelephone { get; set; }
        public string fPhone { get; set; }
        public string fFox { get; set; }
        public string fCity { get; set; }
        public string fAddress { get; set; }
        public byte[] fLoginPassword { get; set; }
        public Nullable<System.DateTime> fUpdateDate { get; set; }
        public string fAuthority { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCase> tCases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCheck> tChecks { get; set; }
        public virtual tEmployee tEmployee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tNew> tNews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tOrder> tOrders { get; set; }
    }
}
