//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tEmployee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tEmployee()
        {
            this.tCustomers = new HashSet<tCustomer>();
            this.tFaceDetections = new HashSet<tFaceDetection>();
            this.tOrderComments = new HashSet<tOrderComment>();
            this.tOrders = new HashSet<tOrder>();
        }
    
        public int fEmployeeID { get; set; }
        public string fName { get; set; }
        public string fLoginPassword { get; set; }
        public Nullable<int> fJobTitleID { get; set; }
        public Nullable<int> fDepartmentID { get; set; }
        public Nullable<System.DateTime> fBirthday { get; set; }
        public string fGender { get; set; }
        public Nullable<System.DateTime> fHireDate { get; set; }
        public string fPhone { get; set; }
        public string fAddress { get; set; }
        public string fEmail { get; set; }
        public Nullable<System.DateTime> fUpdateDate { get; set; }
        public string fUserName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCustomer> tCustomers { get; set; }
        public virtual tDepartment tDepartment { get; set; }
        public virtual tJobTitle tJobTitle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tFaceDetection> tFaceDetections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tOrderComment> tOrderComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tOrder> tOrders { get; set; }
    }
}
