//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tOrderDetail
    {
        public int fID { get; set; }
        public int fOrderID { get; set; }
        public string fProductID { get; set; }
        public decimal fLenght { get; set; }
        public decimal fWidth { get; set; }
        public int fGlassID { get; set; }
        public Nullable<decimal> fDoorPrice { get; set; }
        public Nullable<decimal> fScreenPrice { get; set; }
        public Nullable<decimal> fInstallationPrice { get; set; }
        public Nullable<decimal> fGlassPrice { get; set; }
        public Nullable<decimal> fWaterWayPrice { get; set; }
        public Nullable<decimal> fCrackPrice { get; set; }
        public Nullable<decimal> fSubTotal { get; set; }
        public int fQuantity { get; set; }
    
        public virtual tGlass tGlass { get; set; }
        public virtual tOrder tOrder { get; set; }
        public virtual tProduct tProduct { get; set; }
    }
}
