//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tOrder()
        {
            this.tChecks = new HashSet<tCheck>();
            this.tOrderComments = new HashSet<tOrderComment>();
            this.tOrderDetails = new HashSet<tOrderDetail>();
        }
    
        public int fOrderID { get; set; }
        public Nullable<int> fCustomerID { get; set; }
        public Nullable<int> fEmployeeID { get; set; }
        public System.DateTime fOrderDate { get; set; }
        public System.DateTime fDeliverDate1 { get; set; }
        public Nullable<decimal> fGetMoneyBack1 { get; set; }
        public System.DateTime fDeliverDate2 { get; set; }
        public Nullable<decimal> fGetMoneyBack2 { get; set; }
        public System.DateTime fDeliverDate3 { get; set; }
        public Nullable<decimal> fGetMoneyBack3 { get; set; }
        public System.DateTime fDeliverDate4 { get; set; }
        public Nullable<decimal> fGetMoneyBack4 { get; set; }
        public Nullable<decimal> fMaterialPrice { get; set; }
        public Nullable<double> fDoorFee { get; set; }
        public Nullable<double> fScreenFee { get; set; }
        public Nullable<double> fInstallationFee { get; set; }
        public Nullable<double> fGlassFee { get; set; }
        public Nullable<double> fWaterwayFee { get; set; }
        public Nullable<double> fCrackFee { get; set; }
        public string fOrderConfirm { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCheck> tChecks { get; set; }
        public virtual tCustomer tCustomer { get; set; }
        public virtual tEmployee tEmployee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tOrderComment> tOrderComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tOrderDetail> tOrderDetails { get; set; }
    }
}
