//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tProductList
    {
        public int fID { get; set; }
        public string fProductID { get; set; }
        public string fMaterialID { get; set; }
        public double fQuantity { get; set; }
        public string fType { get; set; }
    
        public virtual tAluminumMaterialList tAluminumMaterialList { get; set; }
        public virtual tProduct tProduct { get; set; }
    }
}
